import { z } from 'zod';
const text = z.string().min(1).max(4096);
const graphColor = z.string().regex(/^#[0-9a-f]{6}$/i);
const graphColors = z.object({ light: z.array(graphColor).min(4).max(16).readonly(), dark: z.array(graphColor).min(4).max(16).readonly() })
  .refine(colors => colors.light.length === colors.dark.length, 'Light and dark graph palettes must have the same size');
export const sessionSchema = z.object({ version: z.literal(2).optional(), diffNavigationScope: z.enum(['commit', 'file']).optional(), appearance: z.object({ theme: z.enum(['system', 'light', 'paper', 'mist', 'dark', 'midnight', 'graphite', 'forest', 'berry', 'contrast']), palette: z.enum(['vivid', 'distinct', 'extended']), codeFont: z.number().int().min(11).max(18), codeRowHeight: z.number().int().min(16).max(36).optional(), fileSpacing: z.number().int().min(0).max(8).optional(), badgeColor: graphColor.optional(), currentBranchColor: graphColor.optional(), currentRepositoryColor: graphColor.optional(), colors: graphColors.optional(), mainColors: z.object({ light: graphColor, dark: graphColor }).optional() }).optional(), language: z.enum(['en', 'zh-CN']).optional(), layout: z.object({ preset: z.enum(['workbench', 'editor']), sidebar: z.number().min(140).max(1200), details: z.number().min(200).max(1600), diff: z.number().min(80).max(1400), diffCollapsed: z.boolean().optional(), graph: z.number().min(40).max(800).optional(), author: z.number().min(60).max(800), date: z.number().min(60).max(800), font: z.number().min(10).max(22), row: z.number().min(20).max(48) }).optional(), repoId: text.optional(), drafts: z.record(z.string().max(128), z.string().max(100000)).optional(), views: z.record(z.string().max(128), z.object({ ref: text.optional(), checkedRefs: z.array(text).max(10000).optional(), expandedRefGroups:z.array(text).max(10000).optional(),collapsedSidebarGroups:z.array(text).max(100).optional(), search: z.string().max(1000), selectedOid: text.optional(), selectedParent: text.optional(), selectedStashOid: text.optional(), selectedFile: text.optional(), tab: z.enum(['history', 'changes']) })).optional() }).refine(state => JSON.stringify(state).length <= 1000000, 'Session exceeds the storage limit');

export type SessionState = z.infer<typeof sessionSchema>;
export type LayoutState = Required<NonNullable<SessionState['layout']>>;

export type DiffNavigationScope = NonNullable<SessionState['diffNavigationScope']>;
