import { useRef, useState } from 'react';
import type { GitAction, Snapshot } from '../src/protocol/types';
import { branchNameConflict, branchNameProblem, type BranchNameProblem } from '../src/protocol/ref-name';
import { remoteNameProblem, remoteUrlProblem } from '../src/protocol/remote';
import { useWorkbench } from './store';
import { demoMode, rpc } from './rpc';
import { useTranslation } from './i18n';
import { Button, Modal } from './ui';
import { samePath } from './pathIdentity';
import { RemoteTrackingDialog } from './RemoteTrackingDialog';
import { captureRemoteLease, updateRemoteLease } from './remoteLease';

export type ActionType = GitAction['type'];
export interface DialogRequest { type: ActionType; target?: string; sources?: string[]; batch?: boolean; paths?: string[]; names?:string[]; expectedOids?:Record<string,string>; expectedDestination?:string; remoteBranches?:string[]; pop?: boolean; expectedOid?: string; remote?: string; branch?: string; checkout?: boolean; candidates?: string[]; returnToPush?:boolean; requireCheckout?:boolean }
export const actionTitles: Partial<Record<ActionType, string>> = { 'branch.create': 'Create Branch', 'branch.checkout': 'Checkout', 'commit.checkout': 'Checkout to Detached HEAD', 'branch.delete': 'Delete Branch', 'remote.add':'Add Remote', 'remote.delete':'Delete Remote Branches', 'tag.create': 'Create Tag', 'tag.delete': 'Delete Tag', 'stash.create': 'Stash Changes', 'stash.apply': 'Apply Stash', 'stash.drop': 'Drop Stash', 'worktree.add': 'Add Worktree', 'worktree.remove': 'Remove Worktree', merge: 'Merge', rebase: 'Rebase', 'cherry-pick': 'Cherry-pick', revert: 'Revert', reset: 'Reset', fetch: 'Fetch', pull: 'Pull', push: 'Push', discard: 'Discard Changes', 'operation.abort': 'Abort' };
function pushDefaults(snapshot: Snapshot, dialog: DialogRequest) {
  const localBranch=dialog.branch??snapshot.branch,ref=snapshot.refs.find(item=>item.kind==='local'&&item.name===localBranch),upstream=ref?.upstream;
  const upstreamRemote=(snapshot.remotes??[]).slice().sort((a,b)=>b.length-a.length).find(remote=>upstream?.startsWith(`${remote}/`));
  const current=localBranch===snapshot.pushTarget?.localBranch?snapshot.pushTarget:undefined;
  const remote=dialog.remote??current?.remote??upstreamRemote??((snapshot.remotes?.length??0)===1?snapshot.remotes![0]:'');
  const remoteBranch=current?.remoteBranch??(upstreamRemote?upstream!.slice(upstreamRemote.length+1):localBranch);
  return {localBranch,remote,remoteBranch,configured:current?.configured??!!upstream};
}
function branchStartLabel(snapshot:Snapshot,start:string,t:(en:string,zh:string)=>string):string {
  const ref=snapshot.refs.find(item=>item.fullName===start);
  if(ref?.kind==='local')return ref.name===snapshot.branch?t(`Current branch ${ref.name} · current version`,`当前分支 ${ref.name} · 当前版本`):t(`Branch ${ref.name}`,`分支 ${ref.name}`);
  if(ref?.kind==='remote')return t(`Remote branch ${ref.name}`,`远程分支 ${ref.name}`);
  if(ref?.kind==='tag')return `Tag ${ref.name}`;
  if(start==='HEAD'||start===snapshot.head)return snapshot.branch?t(`Current branch ${snapshot.branch} · current version`,`当前分支 ${snapshot.branch} · 当前版本`):t('Current Commit','当前 Commit');
  return `Commit ${start.slice(0,12)}`;
}
export function ActionDialog({ dialog, onClose, openAbort, replaceDialog }: { dialog: DialogRequest; onClose(): void; openAbort(): void; replaceDialog(dialog:DialogRequest):void }) {
  if(dialog.type==='branch.track')return <RemoteTrackingDialog dialog={dialog} onClose={onClose}/>;
  return <StandardActionDialog dialog={dialog} onClose={onClose} openAbort={openAbort} replaceDialog={replaceDialog}/>;
}
function StandardActionDialog({ dialog, onClose, openAbort, replaceDialog }: { dialog: DialogRequest; onClose(): void; openAbort(): void; replaceDialog(dialog:DialogRequest):void }) {
  const state = useWorkbench(), snapshot = state.snapshot!, t = useTranslation(), { type } = dialog;
  const local = snapshot.refs.filter(r => r.kind === 'local'), tags = snapshot.refs.filter(r => r.kind === 'tag');
  const push=pushDefaults(snapshot,dialog);
  const stashPaths=type==='stash.create'&&dialog.paths!==undefined?[...new Set(dialog.paths)]:undefined;
  const [stashChoices] = useState(() => snapshot.stashes);
  const [actionContext] = useState(() => ({ expectedHead: snapshot.head ?? '', expectedBranch: snapshot.branch }));
  const [tagChoices] = useState(() => tags.map(tag => ({ ...tag, ...(tag.name === dialog.target && dialog.expectedOid ? { refOid: dialog.expectedOid } : {}) })));
  const [values, setValues] = useState<Record<string, string>>({
    target: dialog.target ?? state.selectedOid ?? snapshot.head ?? 'HEAD', start: dialog.target ?? snapshot.head ?? 'HEAD',
    name: type==='remote.add'?'origin':['branch.checkout','branch.delete','tag.delete'].includes(type) ? dialog.target ?? (type === 'tag.delete' ? tagChoices[0]?.name : local.find(r => r.name !== snapshot.branch)?.name) ?? '' : '',
    selector: dialog.target ?? snapshot.stashes[0]?.selector ?? '', path: type === 'worktree.remove' ? dialog.target ?? '' : '',
    strategy: 'ff-only', mode: 'mixed', remote: type==='push'?push.remote:dialog.remote ?? '', branch: type==='push'?push.localBranch:dialog.branch ?? '', remoteBranch:type==='push'?push.remoteBranch:'', newBranch: '', message: '', mainline: '', url:'',
  });
  const [checks, setChecks] = useState<Record<string, boolean>>({ checkout: dialog.checkout ?? false, includeUntracked: true, pop: !!dialog.pop });
  const [customizePush,setCustomizePush]=useState(()=>type==='push'&&!push.remote);
  const [pushLease, setPushLease] = useState(() => captureRemoteLease(snapshot, push.remote, push.remoteBranch));
  const [validation, setValidation] = useState<string>();
  const [branchTouched,setBranchTouched]=useState(false),branchInput=useRef<HTMLInputElement>(null);
  const set = (key: string, value: string) => { if(key==='selector')useWorkbench.setState({stashApplyFailure:undefined,error:undefined});if(type==='push'&&(key==='remote'||key==='remoteBranch'))setPushLease(previous=>updateRemoteLease(previous,snapshot,key==='remote'?value:values.remote,key==='remoteBranch'?value:values.remoteBranch));setValues(old => ({ ...old, [key]: value })); };
  const field = (key: string, en: string, zh: string = en, options?: { value: string; label: string }[], required = false, hint?: string) => <label className="form-field"><span>{t(en, zh)}</span>{options ? <select aria-label={en} required={required} disabled={state.busy} value={values[key]} onChange={e => set(key,e.target.value)}>{!options.length && <option value="">{t('None available','暂无可用项')}</option>}{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : <input aria-label={en} required={required} disabled={state.busy} value={values[key]} onChange={e => set(key,e.target.value)} placeholder={hint} />}{hint && <small className="muted">{hint}</small>}</label>;
  const checkbox = (key: string, en: string, zh: string = en) => <label className="form-checkbox"><input type="checkbox" checked={!!checks[key]} disabled={state.busy} onChange={e => setChecks(old => ({ ...old,[key]:e.target.checked }))} />{t(en,zh)}</label>;
  const title = type==='stash.create'?stashPaths?t('Stash Selected Files','Stash 所选文件'):t('Stash All Changes','Stash 全部修改'):type === 'branch.create' && dialog.requireCheckout ? t('Create Branch and Checkout','创建分支并切换') : type === 'stash.apply' && checks.pop ? 'Pop Stash' : type==='branch.delete'&&(dialog.names?.length??0)>1?'Delete Branches':actionTitles[type] ?? type;
  const stashFailure=type==='stash.apply'&&state.stashApplyFailure?.selector===values.selector?state.stashApplyFailure:undefined;
  const stashConflictPaths = stashFailure?.conflictPaths ?? [];
  const stashFailurePaths = stashConflictPaths.length ? stashConflictPaths : stashFailure?.paths ?? [];
  const guardedContext = type === 'merge' || type === 'rebase' || type === 'reset';
  const branch = (guardedContext ? actionContext.expectedBranch : snapshot.branch) || 'Detached HEAD';
  const displayTarget = snapshot.refs.find(r => r.fullName === values.target)?.name ?? values.target;
  const branchProblem=type==='branch.create'?branchNameProblem(values.name):undefined;
  const branchConflict=type==='branch.create'&&!branchProblem?branchNameConflict(values.name,local.map(ref=>ref.name)):undefined;
  const missingRemote=type==='push'&&!(snapshot.remotes?.length);
  const branchProblemText=(problem:BranchNameProblem)=>{
    switch(problem){
      case 'empty':return t('Enter a branch name.','请输入分支名称。');
      case 'leading-hyphen':return t('Branch names cannot start with a hyphen.','分支名称不能以连字符开头。');
      case 'space':return t('Branch names cannot contain spaces. Try feature/ux-flow.','分支名称不能包含空格，可用 feature/ux-flow。');
      case 'control':return t('Branch names cannot contain control characters.','分支名称不能包含控制字符。');
      case 'invalid-character':return t('Branch names cannot contain ~, ^, :, ?, *, [, or backslash.','分支名称不能包含 ~、^、:、?、*、[ 或反斜杠。');
      case 'double-dot':return t('Branch names cannot contain two consecutive dots.','分支名称不能包含连续两个点。');
      case 'reflog':return t('Branch names cannot contain @{.','分支名称不能包含 @{。');
      case 'slash':return t('Branch names cannot start or end with a slash, or contain consecutive slashes.','分支名称不能以斜杠开头或结尾，也不能包含连续斜杠。');
      case 'dot-component':return t('Branch name segments cannot start with a dot.','分支名称的各段不能以点开头。');
      case 'lock-suffix':return t('Branch name segments cannot end with .lock.','分支名称的各段不能以 .lock 结尾。');
      case 'trailing-dot':return t('Branch names cannot end with a dot.','分支名称不能以点结尾。');
      case 'single-at':return t('A branch name cannot be only @.','分支名称不能只有 @。');
    }
  };
  const branchValidation=branchProblem?branchProblemText(branchProblem):branchConflict?branchConflict.kind==='exists'?t(`Local branch ${branchConflict.name} already exists. Choose another branch name.`,`本地分支 ${branchConflict.name} 已存在，请使用其他名称。`):t(`Branch name conflicts with existing local branch ${branchConflict.name}. Choose another branch name.`,`分支名称与已有本地分支 ${branchConflict.name} 的路径冲突，请使用其他名称。`):undefined;
  async function executeAction(branchCheckout?:boolean) {
    setValidation(undefined); const v = Object.fromEntries(Object.entries(values).map(([key,value]) => [key,type==='branch.create'&&key==='name'?value:value.trim()])); let action: GitAction;
    if(type==='branch.create'&&branchValidation){setBranchTouched(true);setValidation(branchValidation);branchInput.current?.focus();return;}
    switch(type) {
      case 'fetch': action={type,remote:v.remote || undefined}; break;
      case 'pull': action={type,remote:v.remote || undefined,strategy:v.strategy as 'ff-only'|'merge'|'rebase'}; break;
      case 'push': if(!v.branch||!v.remote||!v.remoteBranch){setValidation(t('Select a local branch, remote, and remote branch.','请选择本地分支、远端和远端分支。'));return;}if(checks.forceWithLease&&(!pushLease.expectedDestination||pushLease.remote!==v.remote||pushLease.remoteBranch!==v.remoteBranch)){setValidation(t('Refresh and reopen the remote target confirmation before Force-with-lease.','请刷新并重新打开远端目标确认后，再执行 Force-with-lease。'));return;} action={type,remote:v.remote,branch:v.branch,remoteBranch:v.remoteBranch,setUpstream:!push.configured,forceWithLease:!!checks.forceWithLease,...(checks.forceWithLease?{expectedOid:pushLease.expectedOid,expectedDestination:pushLease.expectedDestination}:{})}; break;
      case 'remote.add': if(remoteNameProblem(v.name)){setValidation(t('Enter a remote name without spaces, such as origin.','请输入不含空格的远端名称，例如 origin。'));return;}if(remoteUrlProblem(v.url)){setValidation(t('Enter the remote repository URL.','请输入远程仓库地址。'));return;}action={type,name:v.name,url:v.url};break;
      case 'branch.create': action={type,name:v.name,start:v.start || undefined,checkout:dialog.requireCheckout?true:branchCheckout??true}; break;
      case 'branch.checkout': action={type,name:v.name}; break;
      case 'commit.checkout': if(!state.operationSettings.allowDetachedHead){setValidation(t('Direct Detached HEAD Checkout is disabled. Create and switch to a branch.','已禁止直接进入 Detached HEAD，请创建分支并切换。'));return;} action={type,target:v.target}; break;
      case 'branch.delete': action={type,names:dialog.names?.length?dialog.names:[v.name],force:!!checks.force,expectedOids:dialog.expectedOids}; break;
      case 'remote.delete': if(!dialog.remote||!dialog.remoteBranches?.length)return;action={type,remote:dialog.remote,branches:dialog.remoteBranches,expectedOids:dialog.expectedOids,expectedDestination:dialog.expectedDestination};break;
      case 'tag.create': action={type,name:v.name,target:v.target,message:v.message || undefined}; break;
      case 'tag.delete': { const expectedOid=tagChoices.find(tag=>tag.name===v.name)?.refOid; if(!expectedOid){setValidation(t('Refresh and reopen the Tag deletion dialog.','请刷新并重新打开 Tag 删除窗口。'));return;} action={type,name:v.name,expectedOid}; break; }
      case 'stash.create': if(stashPaths&&!stashPaths.length){setValidation(t('Select at least one file to Stash.','请至少选择一个文件进行 Stash。'));return;}action={type,message:v.message || undefined,includeUntracked:stashPaths?true:!!checks.includeUntracked,...(stashPaths?{paths:stashPaths}:{})}; break;
      case 'stash.apply': case 'stash.drop': { const stash=stashChoices.find(s => s.selector===v.selector),expectedOid=v.selector===dialog.target?dialog.expectedOid??stash?.oid:stash?.oid; if(!expectedOid){setValidation(t('Select a Stash and try again.','请选择 Stash 后重试。'));return;} action=type==='stash.apply'?{type,selector:v.selector,pop:!!checks.pop,expectedOid}:{type,selector:v.selector,expectedOid}; break; }
      case 'worktree.add':
        if(!state.operationSettings.allowDetachedHead && (checks.detach || !v.branch && !v.newBranch)){setValidation(t('Choose an existing branch or enter a new branch name. Detached HEAD is disabled.','请选择已有分支或输入新分支名称，当前已禁止 Detached HEAD。'));return;}
        if (v.branch && v.newBranch || checks.detach && (v.branch || v.newBranch)) { setValidation(t('Choose an existing branch, a new branch, or Detached HEAD.','请选择已有分支、新分支或 Detached HEAD 中的一项。')); return; }
        action={type,path:v.path,branch:v.branch || undefined,newBranch:v.newBranch || undefined,start:v.start || undefined,detach:!!checks.detach}; break;
      case 'worktree.remove': action={type,path:v.path,force:!!checks.force}; break;
      case 'merge': case 'rebase': action={type,target:v.target,...actionContext}; break;
      case 'cherry-pick': case 'revert': { const mainline=v.mainline?Number(v.mainline):undefined; if(mainline!==undefined && (!Number.isInteger(mainline)||mainline<1)){setValidation(t('Mainline parent must be a positive integer.','Mainline 父 Commit 序号必须为正整数。'));return;} action={type,commits:v.target.split(/[\s,]+/).filter(Boolean),mainline,expectedHead:snapshot.head,expectedBranch:snapshot.branch||undefined}; break; }
      case 'reset': action={type,target:v.target,mode:v.mode as 'soft'|'mixed'|'hard',...actionContext}; break;
      case 'discard': action={type,paths:dialog.paths ?? []}; break;
      case 'operation.abort': if(!snapshot.operation.kind)return; action={type,kind:snapshot.operation.kind}; break;
      default: return;
    }
    if(await state.execute(action)){if(['branch.checkout','commit.checkout'].includes(action.type)||action.type==='branch.create'&&action.checkout){const latest=useWorkbench.getState();if(latest.repoId===state.repoId&&latest.snapshot?.head)void latest.selectCommit(latest.snapshot.head);}if(action.type==='remote.add'&&dialog.returnToPush)replaceDialog({type:'push',branch:dialog.branch});else onClose();}
  }
  const submit=(event:React.FormEvent)=>{event.preventDefault();void executeAction(type==='branch.create'?true:undefined);};
  const destructive = ['discard','branch.delete','remote.delete','tag.delete','stash.drop','worktree.remove','operation.abort'].includes(type) || type==='reset' && values.mode==='hard';
  if (snapshot.operation.kind && ['merge','rebase','cherry-pick','revert','pull'].includes(type)) {
    const kind=snapshot.operation.kind, files=snapshot.changes.filter(file=>file.conflict);
    return <Modal title={t(`${kind} paused`,`${kind} 已暂停`)} busy={state.busy} onClose={onClose} footer={<>
      <Button disabled={state.busy} onClick={onClose}>{t('Close This Window','关闭此窗口')}</Button>
      <Button className="danger" disabled={state.busy} onClick={openAbort}>{t(`Abort ${kind}…`,`中止本次 ${kind}…`)}</Button>
      <Button className="primary" icon="files" disabled={state.busy} onClick={()=>{onClose();state.selectWorking();const file=files[0]??snapshot.changes.find(file=>file.indexStatus!==' '&&!file.untracked);if(file)state.selectFile({kind:'change',path:file.path,area:file.conflict?'conflict':'staged'});state.setLayout({diffCollapsed:false});}}>{files.length?t('View & Handle Conflicts','查看并处理冲突'):t('Review Staged Result','检查暂存结果')}</Button>
    </>}><p>{snapshot.repository.name} · {branch}</p><p>{t('Closing this window leaves the Git operation paused. Edit and save conflicting files, then return to mark and stage the result.','关闭此窗口后 Git 操作仍处于暂停状态。请编辑保存冲突文件，再返回这里标记并暂存结果。')}</p>{state.error&&<details><summary>{t('Git details','Git 详情')}</summary><pre>{state.error}</pre></details>}</Modal>;
  }
  return <Modal title={title} busy={state.busy} onClose={onClose} footer={stashFailure?<Button onClick={onClose} disabled={state.busy}>{t('Cancel and keep current state','取消并保留当前状态')}</Button>:missingRemote?<><Button onClick={onClose} disabled={state.busy}>{t('Cancel','取消')}</Button><Button className="primary" icon="cloud-upload" disabled={state.busy} onClick={()=>replaceDialog({type:'remote.add',returnToPush:true,branch:values.branch})}>{t('Add Remote…','添加远端…')}</Button></>:type==='branch.create'?<><Button onClick={onClose} disabled={state.busy}>{t('Cancel','取消')}</Button>{!dialog.requireCheckout&&<Button type="button" disabled={state.busy||!!branchValidation} onClick={()=>void executeAction(false)}>{t('Create Only','仅创建')}</Button>}<Button type="submit" form="ag-action-form" className="primary" disabled={state.busy||!!branchValidation}>{state.busy?t('Working…','处理中…'):t('Create and Checkout','创建并切换')}</Button></>:<><Button onClick={onClose} disabled={state.busy}>{t('Cancel','取消')}</Button><Button type="submit" form="ag-action-form" className={destructive?'danger':'primary'} disabled={state.busy}>{state.busy?t('Working…','处理中…'):title}</Button></>}><form id="ag-action-form" className="action-form" onSubmit={submit}>
    <p className="muted">{snapshot.repository.name} · {branch}{guardedContext && <> · HEAD: <code>{actionContext.expectedHead || '(unborn)'}</code></>}</p>
    {type==='branch.create' && <><label className="form-field"><span>{t('Branch Name','分支名称')}</span><input ref={branchInput} aria-label="Branch Name" aria-invalid={branchTouched&&!!branchValidation||undefined} aria-describedby={branchTouched&&branchValidation?'branch-name-error':undefined} required disabled={state.busy} value={values.name} onChange={event=>{setBranchTouched(true);setValidation(undefined);set('name',event.target.value);}} placeholder="feature/my-change"/>{branchTouched&&branchValidation&&<small id="branch-name-error" role="alert" className="form-error">{branchValidation}</small>}</label><div className="branch-start-point"><span>{t('Start Point','起始位置')}</span><strong>{branchStartLabel(snapshot,values.start,t)}</strong>{state.commits.find(commit=>commit.oid===values.start)&&<small>{state.commits.find(commit=>commit.oid===values.start)!.subject}</small>}<small>{dialog.requireCheckout?t('Create and switch to a branch to work on this historical version.','创建并切换到新分支，以使用这个历史版本。'):t('The new branch starts from this selected version.','新分支将从这个选定版本开始。')}</small><details><summary>{t('Git details','Git 详情')}</summary><code>{values.start}</code></details></div></>}
    {(type==='branch.checkout'||type==='branch.delete') && <>{type==='branch.delete'&&dialog.names?.length?<div className="discard-paths">{dialog.names.map(name=><div key={name}>{name}</div>)}</div>:field('name','Branch','分支',(dialog.candidates ? local.filter(r=>dialog.candidates!.includes(r.name)) : local.filter(r=>type!=='branch.delete'||r.name!==snapshot.branch)).map(r=>({value:r.name,label:r.name})),true)}{type==='branch.delete'&&checkbox('force','Force deletion of unmerged branches','强制删除尚未合并的分支')}{type==='branch.checkout'&&<p>{t('Checkout preserves changes when possible; Git stops if they would be overwritten.','Checkout 会尽可能保留修改；可能覆盖修改时 Git 会停止操作。')}</p>}</>}
    {type==='remote.delete'&&<><strong>{t(`Delete from ${dialog.remote}`,`从 ${dialog.remote} 删除`)}</strong><div className="discard-paths">{dialog.remoteBranches?.map(name=><div key={name}>{name}</div>)}</div><p className="warning-text">{t('This deletes branches from the shared remote repository.','此操作会从共享远端仓库删除分支。')}</p></>}
    {type==='remote.add'&&<><p>{t('Connect this local repository to a remote repository. Your local commits are already saved and will not be sent until you Push.','将此本地仓库连接到远程仓库。本地 Commit 已经保存，只有执行 Push 后才会发送。')}</p>{field('name','Remote Name','远端名称',undefined,true,'origin')}{field('url','Repository URL','仓库地址',undefined,true,'https://example.com/owner/repository.git')}</>}
    {type==='commit.checkout'&&<><strong>Checkout {displayTarget.length===40?displayTarget.slice(0,12):displayTarget}</strong><p>{t('This directly enters Detached HEAD. The original branch stays in place; create a branch to keep any new commits.','此操作将直接进入 Detached HEAD。原分支位置不变；若要保留后续提交，请创建分支。')}</p>{!state.operationSettings.allowDetachedHead&&<p role="alert">{t('Direct Detached HEAD Checkout is now disabled.','当前已禁止直接进入 Detached HEAD。')}</p>}</>}
    {type==='tag.create'&&<>{field('name','Tag Name','Tag 名称',undefined,true)}{field('target','Target Commit','目标 Commit',undefined,true)}{field('message','Annotation (optional)','说明（可选）')}</>}
    {type==='tag.delete'&&field('name','Tag','Tag',tagChoices.map(r=>({value:r.name,label:r.name})),true)}
    {type==='stash.create'&&<>{stashPaths&&<><strong>{t(`${stashPaths.length} selected file${stashPaths.length===1?'':'s'}`,`已选择 ${stashPaths.length} 个文件`)}</strong><div className="discard-paths">{stashPaths.map(path=><div key={path}>{path}</div>)}</div></>}{field('message','Description (optional)','说明（可选）')}{!stashPaths&&checkbox('includeUntracked','Include untracked files','包含未跟踪文件')}<p>{stashPaths?t('Save each selected file’s complete Index and Working Tree state, even when selected from only Staged or Unstaged Changes. Selected untracked files are included. Other files keep their changes.','保存每个所选文件完整的 Index 和工作区状态，即使只在 Staged 或 Unstaged Changes 中选择。所选未跟踪文件一并保存，其他文件的修改保留。'):t('Save all tracked files’ Index and Working Tree changes for later, then clear their saved changes from the project.','保存全部已跟踪文件的 Index 和工作区修改供之后恢复，并清理这些已保存的修改。')}</p></>}
    {(type==='stash.apply'||type==='stash.drop')&&<>{field('selector','Stash','Stash',stashChoices.map(s=>({value:s.selector,label:`${s.selector}: ${s.subject}`})),true)}<p>{type==='stash.drop'?t('Remove this entry. Its saved changes may become unreachable.','移除此条目；其中保存的修改可能无法恢复。'):checks.pop?t('Restore the saved Index and Working Tree state, then remove the Stash only on success. Preflight conflicts stop the entire restore and preserve the current state and entry.','恢复保存的 Index 和工作区状态，仅在成功后删除 Stash。预检发现冲突时停止整次恢复，保留当前现场和存档。'):t('Restore the saved Index and Working Tree state and keep this Stash. Preflight conflicts stop the entire restore without changing the current state.','恢复保存的 Index 和工作区状态，并保留此 Stash。预检发现冲突时停止整次恢复，当前现场不变。')}</p>{stashFailure&&<section className="stash-apply-blocker" role="alert"><strong>{stashFailure.reason==='untracked-path-exists'?t('Cannot restore because these files already exist in the project.','无法恢复，因为项目中已存在以下文件。'):stashFailure.reason==='restore-conflict'?t('Restore stopped because preflight found conflicts.','预检发现冲突，已停止恢复。'):stashFailure.reason==='state-changed'?t('Restore stopped because the project changed during preflight.','预检期间项目发生变化，已停止恢复。'):t('Restore stopped because preflight could not restore the saved state.','预检无法恢复保存的现场，已停止恢复。')}</strong><p>{t('This restore did not change the Index or Working Tree. The Stash is still saved. Compare or open a file before deciding how to resolve the blocker.','本次恢复未改动 Index 和工作区，Stash 存档仍然保留。请先比较或打开文件，再决定如何处理阻碍。')}</p><strong>{stashFailure.reason==='untracked-path-exists'?t('Existing paths blocking this restore','阻止恢复的现有路径'):stashConflictPaths.length?t('Confirmed conflicting files','已确认的冲突文件'):t('Files included in this restore','本次恢复涉及的文件')}</strong><div className="stash-conflict-files">{stashFailurePaths.map(path=><div className="stash-conflict-file" key={path}><code>{path}</code><div><Button type="button" className="icon-only" icon="diff" title={t('Compare saved and existing file','比较收起内容与现有文件')} aria-label={`${t('Compare saved and existing file','比较收起内容与现有文件')}: ${path}`} onClick={()=>void rpc('diff',state.repoId,{kind:'stash-working',stashOid:stashFailure.stashOid,path}).catch(state.report)}/><Button type="button" className="icon-only" icon="go-to-file" title={t('Open existing file','打开现有文件')} aria-label={`${t('Open existing file','打开现有文件')}: ${path}`} onClick={()=>void rpc('openFile',state.repoId,{path}).catch(state.report)}/></div></div>)}</div><p className="muted">{t('Resolve the blocker, then close and retry the restore to run preflight again.','处理阻碍后，关闭弹窗并重新恢复，以再次预检。')}</p>{(stashFailure.output||state.error)&&<details><summary>{t('Git details','Git 详情')}</summary><pre>{stashFailure.output||state.error}</pre></details>}</section>}</>}
    {type==='worktree.add'&&<>{field('path','Worktree Folder','Worktree 目录',undefined,true)}<Button type="button" icon="folder-opened" onClick={()=>void rpc<string|undefined>('pickWorktree',state.repoId,{}).then(path=>{if(path)set('path',path);}).catch(state.report)}>{t('Browse…','浏览…')}</Button>{field('branch','Existing Branch','已有分支',[{value:'',label:t('None','无')},...local.map(r=>({value:r.name,label:r.name}))])}{field('newBranch',state.operationSettings.allowDetachedHead?'New Branch (optional)':'New Branch','新分支')}{field('start','Start Point','起始位置')}{state.operationSettings.allowDetachedHead?checkbox('detach','Detached HEAD'):<p className="muted">{t('Choose an existing branch or create a new one. Detached HEAD is disabled in Settings > Advanced.','请选择已有分支或创建新分支；设置 → 高级中默认禁止 Detached HEAD。')}</p>}</>}
    {type==='worktree.remove'&&<>{field('path','Worktree','Worktree',snapshot.worktrees.filter(w=>!samePath(w.path,snapshot.repository.root)&&!w.locked&&w!==snapshot.worktrees[0]).map(w=>({value:w.path,label:w.path})),true)}{checkbox('force','Remove even with uncommitted changes','强制移除，包括未提交修改')}</>}
    {(type==='merge'||type==='rebase')&&<>{field('target',type==='merge'?'Merge Source':'New Base',type==='merge'?'Merge 来源':'新的基点',undefined,true)}<strong>{type==='merge'?`Merge ${displayTarget} into ${branch}`:`Rebase ${branch} onto ${displayTarget}`}</strong><p>{type==='merge'?t('Bring selected history into the current branch.','将选中的历史 Merge 到当前分支。'):t('Replay current-branch commits onto the selected base. Replayed Commit IDs change.','将当前分支的 Commit 重新应用到选定基点；这些 Commit 的 ID 会改变。')}</p></>}
    {(type==='cherry-pick'||type==='revert')&&<>{field('target','Commit IDs','Commit ID',undefined,true)}{field('mainline','Mainline Parent (Merge Commits only)','Mainline 父 Commit（仅 Merge Commit）')}<strong>{type==='cherry-pick'?`Cherry-pick ${displayTarget} onto ${branch}`:`Revert ${displayTarget} on ${branch}`}</strong><p>{type==='revert'?t('Create new commits reversing these changes.','生成新的 Commit 撤销这些修改。'):t('Apply these commits to the current branch in the entered order.','按输入顺序将这些 Commit 应用到当前分支。')}</p></>}
    {type==='reset'&&<>{field('target','Target Commit','目标 Commit',undefined,true)}{field('mode','Reset Mode','Reset 模式',[{value:'soft',label:'Soft'},{value:'mixed',label:'Mixed'},{value:'hard',label:'Hard'}])}<strong>Reset {branch} to {displayTarget}</strong><p className={values.mode==='hard'?'warning-text':''}>{values.mode==='soft'?t('Keep Index and Working Tree changes.','保留 Index 和工作区修改。'):values.mode==='mixed'?t('Reset Index; keep Working Tree changes.','重置 Index；保留工作区修改。'):t('Reset Index and tracked Working Tree files. Uncommitted tracked changes will be lost.','重置 Index 和工作区中的已跟踪文件；这些文件的未提交修改将丢失。')}</p></>}
    {['fetch','pull'].includes(type)&&<>{field('remote','Remote (optional)','远端（可选）')}{type==='pull'&&field('strategy','Pull Strategy','Pull 策略',[{value:'ff-only',label:'Fast-forward Only'},{value:'merge',label:'Merge'},{value:'rebase',label:'Rebase'}])}</>}
    {type==='push'&&(missingRemote?<section className="push-prerequisite" role="status"><strong>{t('No remote repository is connected yet.','尚未连接远程仓库。')}</strong><p>{t('Your commits are saved locally. Add a remote address before sending them with Push.','你的 Commit 已保存在本地。请先添加远端地址，再通过 Push 发送。')}</p></section>:<><div className="push-target"><span>{t('Push Target','Push 目标')}</span><strong>{values.branch} <span aria-hidden="true">→</span> {values.remote?`${values.remote}/${values.remoteBranch}`:t('Select remote','选择远端')}</strong><dl><div><dt>{t('Local Branch','本地分支')}</dt><dd>{values.branch}</dd></div><div><dt>{t('Remote','远端')}</dt><dd>{values.remote||'—'}</dd></div><div><dt>{t('Remote Branch','远端分支')}</dt><dd>{values.remoteBranch||'—'}</dd></div></dl></div>{(!customizePush||!!push.remote)&&<Button type="button" icon="settings-gear" onClick={()=>{setCustomizePush(value=>!value);if(customizePush){setValues(old=>({...old,remote:push.remote,remoteBranch:push.remoteBranch}));setPushLease(previous=>updateRemoteLease(previous,snapshot,push.remote,push.remoteBranch));}}}>{customizePush?t('Use Default Target','使用默认目标'):t('Change Target…','更改目标…')}</Button>}{customizePush&&<>{field('remote','Remote','远端',[{value:'',label:t('Select remote…','选择远端…')},...[...new Set([values.remote,...(snapshot.remotes??[])].filter(Boolean))].map(remote=>({value:remote,label:remote}))],true)}{field('remoteBranch','Remote Branch','远端分支',undefined,true)}</>}<details className="advanced-options"><summary>{t('Advanced Options','高级选项')}</summary>{checkbox('forceWithLease','Force-with-lease')}{checks.forceWithLease&&<><p className="warning-text">{t('This may replace remote branch history, but only if its version still matches the target confirmed in this dialog.','这可能覆盖远端分支历史，但仅在远端版本仍与本窗口确认的目标版本一致时执行。')}</p><p>{pushLease.expectedOid?<>{t('Expected remote Commit: ','确认的远端 Commit：')}<code>{pushLease.expectedOid.slice(0,12)}</code></>:t('Create only if this remote branch is still absent.','仅在此远端分支仍不存在时创建。')}</p></>}</details>{!push.configured&&<p className="muted">{t('This Push will set the selected target as the upstream branch.','本次 Push 会将所选目标设置为 upstream 分支。')}</p>}</>)}
    {type==='discard'&&<><div className="discard-paths">{dialog.paths?.map(path=><div key={path}>{path}</div>)}</div><p className="warning-text">{t('Discard Unstaged Changes and selected untracked files. Staged Changes remain in the Index.','丢弃 Unstaged Changes 和选中的未跟踪文件。Index 中的 Staged Changes 保留。')}</p></>}
    {type==='operation.abort'&&<><p className="warning-text">{t(`Abort the active ${snapshot.operation.kind}; edits made while resolving conflicts may be discarded. Closing this window does not abort.`,`中止当前 ${snapshot.operation.kind}；解决冲突期间的修改可能被丢弃。关闭此窗口不会中止操作。`)}</p>{snapshot.operation.originalHead&&<p>{t('Git will attempt to restore the operation start state at Commit ','Git 将尝试恢复到操作开始时的状态，Commit ')}<code>{snapshot.operation.originalHead}</code>{t('. Pre-existing local changes may prevent a full restoration.','。操作前已有的本地修改可能影响完整恢复。')}</p>}</>}
    {validation&&!(type==='branch.create'&&branchValidation)&&<p role="alert" className="form-error">{validation}</p>}{state.error&&!stashFailure&&(type==='branch.create'?<details><summary>{t('Git details','Git 详情')}</summary><pre>{state.error}</pre></details>:<p role="alert" className="form-error">{state.error}</p>)}{demoMode&&<p className="muted">{t('Demo: sample data only.','模拟操作：仅修改示例数据。')}</p>}
  </form></Modal>;
}
