import { useEffect, useMemo, useRef, useState } from 'react';
import type { AddRepositoriesResult, RepositoryCollection, RepositoryDiscoveryPreview } from '../src/protocol/types';
import { rpc, subscribe } from './rpc';
import { useTranslation } from './i18n';
import { Button, Icon, Modal } from './ui';
import { useWorkbench } from './store';
import { selectionForClick } from './commitSelection';

type Phase='choose'|'scanning'|'results'|'submitting';
type AddMode='repository'|'group';

export function RepositoryDialog({onClose}:{onClose():void}){
  const state=useWorkbench(),t=useTranslation(),[phase,setPhase]=useState<Phase>('choose'),[root,setRoot]=useState(''),[preview,setPreview]=useState<RepositoryDiscoveryPreview>(),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[collectionId,setCollectionId]=useState(''),[createGroup,setCreateGroup]=useState(false),[groupName,setGroupName]=useState(''),[progress,setProgress]=useState({scanned:0,found:0}),[error,setError]=useState<string>(),scanId=useRef<string|undefined>(undefined),generation=useRef(0),anchor=useRef<string|undefined>(undefined);
  const [mode,setMode]=useState<AddMode>('repository'),[newName,setNewName]=useState(''),[creating,setCreating]=useState(false),[picking,setPicking]=useState(false),groupInput=useRef<HTMLInputElement>(null),busy=creating||phase==='submitting';
  useEffect(()=>{if(mode==='group')groupInput.current?.focus();},[mode]);
  const nameProblem=(value:string)=>{const name=value.trim();return !name?t('Enter a group name.','请输入分组名称。'):name.length>80?t('Use no more than 80 characters.','分组名称不能超过 80 个字符。'):state.repositoryCollections.some(collection=>collection.name.localeCompare(name,undefined,{sensitivity:'accent'})===0)?t('A group with this name already exists.','已存在同名分组。'):undefined;};
  const newNameProblem=newName?nameProblem(newName):undefined;
  useEffect(()=>subscribe(event=>{if(event.type==='repositoryDiscoveryProgress'&&event.scanId===scanId.current)setProgress({scanned:event.scanned,found:event.found});}),[]);
  const available=preview?.candidates.filter(candidate=>!candidate.existing)??[],filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase();return preview?.candidates.filter(candidate=>!query||candidate.name.toLocaleLowerCase().includes(query)||candidate.path.toLocaleLowerCase().includes(query))??[];},[preview,search]),selectedSet=new Set(selected),allSelected=available.length>0&&available.every(candidate=>selectedSet.has(candidate.key));
  const stopScan=()=>{generation.current++;const id=scanId.current;scanId.current=undefined;if(id)void rpc('cancelRepositoryDiscovery',undefined,{scanId:id});};
  const close=()=>{stopScan();onClose();};
  const switchMode=(next:AddMode)=>{if(busy||next===mode)return;generation.current++;if(phase==='scanning'){stopScan();setPhase('choose');}setError(undefined);setMode(next);};
  const createCollection=async()=>{const problem=nameProblem(newName);if(problem){setError(problem);return;}if(busy)return;setError(undefined);setCreating(true);try{const collection=await rpc<RepositoryCollection>('createRepositoryCollection',undefined,{name:newName.trim()});await state.initialize();useWorkbench.setState({notice:t(`Created group ${collection.name}.`,`已创建分组“${collection.name}”。`)});close();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setCreating(false);}};
  const scan=async(path:string)=>{stopScan();const request=++generation.current,id=`scan-${Date.now()}-${request}`;scanId.current=id;setRoot(path);setPreview(undefined);setSelected([]);setSearch('');setProgress({scanned:0,found:0});setError(undefined);setPhase('scanning');try{const result=await rpc<RepositoryDiscoveryPreview>('discoverRepositories',undefined,{scanId:id,path});if(request!==generation.current)return;if(result.cancelled){setPhase('choose');return;}setPreview(result);setSelected(result.candidates.filter(candidate=>!candidate.existing).map(candidate=>candidate.key));setPhase('results');}catch(reason){if(request!==generation.current)return;setError(reason instanceof Error?reason.message:String(reason));setPhase('choose');}};
  const choose=async()=>{if(picking)return;const request=++generation.current;setPicking(true);setError(undefined);try{const path=await rpc<string|undefined>('pickRepositoryDirectory');if(path&&request===generation.current)await scan(path);}catch(reason){if(request===generation.current)setError(reason instanceof Error?reason.message:String(reason));}finally{setPicking(false);}};
  const cancelScan=()=>{stopScan();setPhase('choose');setProgress({scanned:0,found:0});};
  const toggle=(key:string,event:{shiftKey:boolean;ctrlKey:boolean;metaKey:boolean})=>{const order=filtered.filter(candidate=>!candidate.existing).map(candidate=>candidate.key),next=selectionForClick(order,selected,anchor.current,key,{toggle:event.ctrlKey||event.metaKey,range:event.shiftKey});setSelected(next.selected);anchor.current=next.anchor;};
  const add=async()=>{if(!selected.length||busy)return;if(createGroup&&nameProblem(groupName)){setError(nameProblem(groupName));return;}setError(undefined);setPhase('submitting');try{const result=await rpc<AddRepositoriesResult>('addRepository',undefined,{scanId:scanId.current,keys:selected,...(!createGroup&&collectionId?{collectionId}:{}),...(createGroup?{newCollectionName:groupName.trim()}: {})});await state.initialize();useWorkbench.setState({notice:t(`Added ${result.added} repositories${result.collection?` to ${result.collection.name}`:''}.${result.existing?` ${result.existing} already added.`:''}${result.skipped?` Skipped ${result.skipped}.`:''}`,`已添加 ${result.added} 个仓库${result.collection?`到“${result.collection.name}”`:''}。${result.existing?`${result.existing} 个已存在。`:''}${result.skipped?`跳过 ${result.skipped} 项。`:''}`),selectedRepositoryKeys:[],repositorySelectionAnchor:undefined});scanId.current=undefined;onClose();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setPhase('results');}};
  const footer=phase==='choose'?<><Button onClick={close}>{t('Cancel','取消')}</Button><Button className="primary" icon="folder-opened" disabled={picking} onClick={()=>void choose()}>{t('Choose Folder…','选择文件夹…')}</Button></>:phase==='scanning'?<Button onClick={cancelScan}>{t('Cancel Scan','取消扫描')}</Button>:<><span className="repository-add-summary" aria-live="polite">{t(`${selected.length} selected`,`已选 ${selected.length} 项`)}</span><Button onClick={close} disabled={phase==='submitting'}>{t('Cancel','取消')}</Button><Button className="primary" onClick={()=>void add()} disabled={!selected.length||phase==='submitting'||createGroup&&!!nameProblem(groupName)}>{phase==='submitting'?t('Adding…','正在添加…'):t(`Add ${selected.length} Repositories`,`添加 ${selected.length} 个仓库`)}</Button></>;
  const groupFooter=<><Button onClick={close} disabled={busy}>{t('Cancel','取消')}</Button><Button type="submit" form="repository-create-group" className="primary" icon="new-folder" disabled={busy||!!nameProblem(newName)}>{creating?t('Creating…','正在创建…'):t('Create Group','创建分组')}</Button></>;
  return <Modal title={t('Add','添加')} className="repository-dialog" onClose={close} busy={busy} footer={mode==='group'?groupFooter:footer}>
    <div className="repository-add-tabs settings-tabs" role="tablist" aria-label={t('Add type','添加类型')} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();switchMode(event.key==='Home'?'repository':event.key==='End'?'group':mode==='repository'?'group':'repository');}}}>
      <button type="button" id="add-repository-tab" role="tab" aria-selected={mode==='repository'} aria-controls="repository-add-panel" tabIndex={mode==='repository'?0:-1} className={mode==='repository'?'is-active':''} disabled={busy} onClick={()=>switchMode('repository')}><Icon name="repo"/>{t('Add Repository','添加仓库')}</button>
      <button type="button" id="add-group-tab" role="tab" aria-selected={mode==='group'} aria-controls="repository-add-panel" tabIndex={mode==='group'?0:-1} className={mode==='group'?'is-active':''} disabled={busy} onClick={()=>switchMode('group')}><Icon name="new-folder"/>{t('Add Group','添加分组')}</button>
    </div>
    {error&&<div className="banner error" role="alert"><span>{error}</span></div>}
    <div id="repository-add-panel" className="repository-add-panel" role="tabpanel" aria-labelledby={mode==='group'?'add-group-tab':'add-repository-tab'}>
    {mode==='group'?<form id="repository-create-group" className="repository-group-form" onSubmit={event=>{event.preventDefault();void createCollection();}}>
      <p className="repository-dialog-intro">{t('Create a group to organize repositories. You can add or move repositories into it later.','创建分组来整理仓库，之后可以向其中添加或移动仓库。')}</p>
      <label className="form-field"><span>{t('Group name','分组名称')}</span><input ref={groupInput} value={newName} maxLength={80} disabled={busy} aria-invalid={!!newNameProblem||!!error} aria-describedby={newNameProblem?'repository-group-error':undefined} onChange={event=>{setNewName(event.target.value);setError(undefined);}}/></label>
      {newNameProblem&&<div id="repository-group-error" className="repository-name-error" role="alert">{newNameProblem}</div>}
    </form>:<>
    <p className="repository-dialog-intro">{t('Choose one folder. AlwayGit recursively finds Git repositories below it, then adds only the repositories you confirm.','选择一个文件夹。AlwayGit 会递归查找其中的 Git 仓库，并且只添加你确认的项目。')}</p>
    {phase==='choose'&&<div className="repository-folder-empty"><Icon name="folder-opened"/><strong>{root?t('Choose another folder or scan this folder again.','可以选择其他文件夹，或者重新扫描当前文件夹。'):t('No folder selected','尚未选择文件夹')}</strong>{root&&<code>{root}</code>}</div>}
    {phase==='scanning'&&<div className="repository-scanning" aria-live="polite"><Icon name="loading" className="feedback-spinner"/><div><strong>{t('Scanning for Git repositories…','正在扫描 Git 仓库…')}</strong><code>{root}</code><span>{t(`Scanned ${progress.scanned} folders · found ${progress.found} repositories`,`已扫描 ${progress.scanned} 个文件夹 · 找到 ${progress.found} 个仓库`)}</span></div></div>}
    {(phase==='results'||phase==='submitting')&&preview&&<>
      <div className="repository-scan-header"><div><span>{t('Scan folder','扫描目录')}</span><code title={root}>{root}</code></div><Button className="icon-only" icon="folder-opened" title={t('Choose another folder','选择其他文件夹')} aria-label={t('Choose another folder','选择其他文件夹')} disabled={phase==='submitting'||picking} onClick={()=>void choose()}/></div>
      <div className="repository-result-summary"><strong>{t(`Found ${preview.candidates.length} repositories`,`找到 ${preview.candidates.length} 个仓库`)}</strong><span>{t(`${available.length} available · ${preview.candidates.length-available.length} already added`,`${available.length} 个可添加 · ${preview.candidates.length-available.length} 个已添加`)}</span></div>
      {preview.candidates.length?<><div className="repository-result-tools"><label><Icon name="search"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('Filter repositories','筛选仓库')} aria-label={t('Filter repositories','筛选仓库')}/></label><label className="form-checkbox"><input type="checkbox" checked={allSelected} onChange={event=>setSelected(event.target.checked?available.map(candidate=>candidate.key):[])}/>{t('Select all available','全选可添加项')}</label></div>
      <div className="repository-candidate-list" role="listbox" aria-multiselectable="true" aria-label={t('Discovered repositories','扫描到的仓库')}>{filtered.length?filtered.map(candidate=><label key={candidate.key} className={`repository-candidate ${candidate.existing?'existing':''}`} role="option" aria-selected={!candidate.existing&&selectedSet.has(candidate.key)}><input type="checkbox" disabled={candidate.existing||phase==='submitting'} checked={!candidate.existing&&selectedSet.has(candidate.key)} readOnly onClick={event=>{event.preventDefault();toggle(candidate.key,event);}}/><span><strong>{candidate.name}</strong><code title={candidate.path}>{candidate.path}</code></span><small>{candidate.existing?t('Already added','已添加'):t('Available','可添加')}</small></label>):<div className="repository-filter-empty">{t('No repositories match this filter.','没有匹配当前筛选条件的仓库。')}</div>}</div></>:<div className="repository-result-empty"><Icon name="search-stop"/><strong>{t('No Git repositories found','没有找到 Git 仓库')}</strong><span>{t('Choose a different folder and try again.','请选择其他文件夹后重试。')}</span></div>}
      {!!preview.issues.length&&<details className="repository-scan-issues"><summary>{t(`${preview.issues.length} folders or repositories were skipped`,`${preview.issues.length} 个文件夹或仓库已跳过`)}</summary>{preview.issues.map(issue=><div key={`${issue.path}:${issue.message}`}><code>{issue.path}</code><span>{issue.message}</span></div>)}</details>}
      {!!available.length&&<div className="repository-destination"><label className="form-field"><span>{t('Add to','添加到')}</span><select value={collectionId} onChange={event=>setCollectionId(event.target.value)} disabled={createGroup||phase==='submitting'}><option value="">{t('Repository root','仓库根层')}</option>{state.repositoryCollections.map(collection=><option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label><Button className="repository-new-group" icon="new-folder" aria-expanded={createGroup} onClick={()=>setCreateGroup(current=>!current)} disabled={phase==='submitting'}>{createGroup?t('Use Existing Group','使用现有分组'):t('New Group','新建分组')}</Button>{createGroup&&<label className="form-field"><span>{t('New group name','新分组名称')}</span><input value={groupName} maxLength={80} onChange={event=>setGroupName(event.target.value)} data-autofocus="true"/></label>}</div>}
    </>}
    </>}
    </div>
  </Modal>;
}
