import { useEffect, useMemo, useRef, useState } from 'react';
import type { AddRepositoriesResult, RepositoryDiscoveryPreview } from '../src/protocol/types';
import { rpc, subscribe } from './rpc';
import { useTranslation } from './i18n';
import { Button, Icon, Modal } from './ui';
import { useWorkbench } from './store';
import { selectionForClick } from './commitSelection';

type Phase='choose'|'scanning'|'results'|'submitting';

export function RepositoryDialog({onClose}:{onClose():void}){
  const state=useWorkbench(),t=useTranslation(),[phase,setPhase]=useState<Phase>('choose'),[root,setRoot]=useState(''),[preview,setPreview]=useState<RepositoryDiscoveryPreview>(),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[collectionId,setCollectionId]=useState(''),[createGroup,setCreateGroup]=useState(false),[groupName,setGroupName]=useState(''),[progress,setProgress]=useState({scanned:0,found:0}),[error,setError]=useState<string>(),scanId=useRef<string|undefined>(undefined),generation=useRef(0),anchor=useRef<string|undefined>(undefined);
  useEffect(()=>subscribe(event=>{if(event.type==='repositoryDiscoveryProgress'&&event.scanId===scanId.current)setProgress({scanned:event.scanned,found:event.found});}),[]);
  const available=preview?.candidates.filter(candidate=>!candidate.existing)??[],filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase();return preview?.candidates.filter(candidate=>!query||candidate.name.toLocaleLowerCase().includes(query)||candidate.path.toLocaleLowerCase().includes(query))??[];},[preview,search]),selectedSet=new Set(selected),allSelected=available.length>0&&available.every(candidate=>selectedSet.has(candidate.key));
  const stopScan=()=>{generation.current++;const id=scanId.current;scanId.current=undefined;if(id)void rpc('cancelRepositoryDiscovery',undefined,{scanId:id});};
  const close=()=>{stopScan();onClose();};
  const scan=async(path:string)=>{stopScan();const request=++generation.current,id=`scan-${Date.now()}-${request}`;scanId.current=id;setRoot(path);setPreview(undefined);setSelected([]);setSearch('');setProgress({scanned:0,found:0});setError(undefined);setPhase('scanning');try{const result=await rpc<RepositoryDiscoveryPreview>('discoverRepositories',undefined,{scanId:id,path});if(request!==generation.current)return;if(result.cancelled){setPhase('choose');return;}setPreview(result);setSelected(result.candidates.filter(candidate=>!candidate.existing).map(candidate=>candidate.key));setPhase('results');}catch(reason){if(request!==generation.current)return;setError(reason instanceof Error?reason.message:String(reason));setPhase('choose');}};
  const choose=async()=>{setError(undefined);try{const path=await rpc<string|undefined>('pickRepositoryDirectory');if(path)await scan(path);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}};
  const cancelScan=()=>{stopScan();setPhase('choose');setProgress({scanned:0,found:0});};
  const toggle=(key:string,event:{shiftKey:boolean;ctrlKey:boolean;metaKey:boolean})=>{const order=filtered.filter(candidate=>!candidate.existing).map(candidate=>candidate.key),next=selectionForClick(order,selected,anchor.current,key,{toggle:event.ctrlKey||event.metaKey,range:event.shiftKey});setSelected(next.selected);anchor.current=next.anchor;};
  const add=async()=>{if(!selected.length)return;setError(undefined);setPhase('submitting');try{const result=await rpc<AddRepositoriesResult>('addRepository',undefined,{scanId:scanId.current,keys:selected,...(!createGroup&&collectionId?{collectionId}:{}),...(createGroup?{newCollectionName:groupName.trim()}: {})});await state.initialize();useWorkbench.setState({notice:t(`Added ${result.added} repositories${result.collection?` to ${result.collection.name}`:''}.${result.existing?` ${result.existing} already added.`:''}${result.skipped?` Skipped ${result.skipped}.`:''}`,`已添加 ${result.added} 个仓库${result.collection?`到“${result.collection.name}”`:''}。${result.existing?`${result.existing} 个已存在。`:''}${result.skipped?`跳过 ${result.skipped} 项。`:''}`),selectedRepositoryKeys:[],repositorySelectionAnchor:undefined});scanId.current=undefined;onClose();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setPhase('results');}};
  const footer=phase==='choose'?<><Button onClick={close}>{t('Cancel','取消')}</Button><Button className="primary" icon="folder-opened" onClick={()=>void choose()}>{t('Choose Folder…','选择文件夹…')}</Button></>:phase==='scanning'?<Button onClick={cancelScan}>{t('Cancel Scan','取消扫描')}</Button>:<><span className="repository-add-summary" aria-live="polite">{t(`${selected.length} selected`,`已选 ${selected.length} 项`)}</span><Button onClick={close} disabled={phase==='submitting'}>{t('Cancel','取消')}</Button><Button className="primary" onClick={()=>void add()} disabled={!selected.length||phase==='submitting'||createGroup&&!groupName.trim()}>{phase==='submitting'?t('Adding…','正在添加…'):t(`Add ${selected.length} Repositories`,`添加 ${selected.length} 个仓库`)}</Button></>;
  return <Modal title={t('Add Repositories','添加仓库')} className="repository-dialog" onClose={close} busy={phase==='submitting'} footer={footer}>
    <p className="repository-dialog-intro">{t('Choose one folder. AlwayGit recursively finds Git repositories below it, then adds only the repositories you confirm.','选择一个文件夹。AlwayGit 会递归查找其中的 Git 仓库，并且只添加你确认的项目。')}</p>
    {error&&<div className="banner error" role="alert"><span>{error}</span></div>}
    {phase==='choose'&&<div className="repository-folder-empty"><Icon name="folder-opened"/><strong>{root?t('Choose another folder or scan this folder again.','可以选择其他文件夹，或者重新扫描当前文件夹。'):t('No folder selected','尚未选择文件夹')}</strong>{root&&<code>{root}</code>}</div>}
    {phase==='scanning'&&<div className="repository-scanning" aria-live="polite"><Icon name="loading" className="feedback-spinner"/><div><strong>{t('Scanning for Git repositories…','正在扫描 Git 仓库…')}</strong><code>{root}</code><span>{t(`Scanned ${progress.scanned} folders · found ${progress.found} repositories`,`已扫描 ${progress.scanned} 个文件夹 · 找到 ${progress.found} 个仓库`)}</span></div></div>}
    {(phase==='results'||phase==='submitting')&&preview&&<>
      <div className="repository-scan-header"><div><span>{t('Scan folder','扫描目录')}</span><code title={root}>{root}</code></div><Button className="icon-only" icon="folder-opened" title={t('Choose another folder','选择其他文件夹')} aria-label={t('Choose another folder','选择其他文件夹')} disabled={phase==='submitting'} onClick={()=>void choose()}/></div>
      <div className="repository-result-summary"><strong>{t(`Found ${preview.candidates.length} repositories`,`找到 ${preview.candidates.length} 个仓库`)}</strong><span>{t(`${available.length} available · ${preview.candidates.length-available.length} already added`,`${available.length} 个可添加 · ${preview.candidates.length-available.length} 个已添加`)}</span></div>
      {preview.candidates.length?<><div className="repository-result-tools"><label><Icon name="search"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t('Filter repositories','筛选仓库')} aria-label={t('Filter repositories','筛选仓库')}/></label><label className="form-checkbox"><input type="checkbox" checked={allSelected} onChange={event=>setSelected(event.target.checked?available.map(candidate=>candidate.key):[])}/>{t('Select all available','全选可添加项')}</label></div>
      <div className="repository-candidate-list" role="listbox" aria-multiselectable="true" aria-label={t('Discovered repositories','扫描到的仓库')}>{filtered.length?filtered.map(candidate=><label key={candidate.key} className={`repository-candidate ${candidate.existing?'existing':''}`} role="option" aria-selected={!candidate.existing&&selectedSet.has(candidate.key)}><input type="checkbox" disabled={candidate.existing||phase==='submitting'} checked={!candidate.existing&&selectedSet.has(candidate.key)} readOnly onClick={event=>{event.preventDefault();toggle(candidate.key,event);}}/><span><strong>{candidate.name}</strong><code title={candidate.path}>{candidate.path}</code></span><small>{candidate.existing?t('Already added','已添加'):t('Available','可添加')}</small></label>):<div className="repository-filter-empty">{t('No repositories match this filter.','没有匹配当前筛选条件的仓库。')}</div>}</div></>:<div className="repository-result-empty"><Icon name="search-stop"/><strong>{t('No Git repositories found','没有找到 Git 仓库')}</strong><span>{t('Choose a different folder and try again.','请选择其他文件夹后重试。')}</span></div>}
      {!!preview.issues.length&&<details className="repository-scan-issues"><summary>{t(`${preview.issues.length} folders or repositories were skipped`,`${preview.issues.length} 个文件夹或仓库已跳过`)}</summary>{preview.issues.map(issue=><div key={`${issue.path}:${issue.message}`}><code>{issue.path}</code><span>{issue.message}</span></div>)}</details>}
      {!!available.length&&<div className="repository-destination"><label className="form-field"><span>{t('Add to','添加到')}</span><select value={collectionId} onChange={event=>setCollectionId(event.target.value)} disabled={createGroup||phase==='submitting'}><option value="">{t('Repository root','仓库根层')}</option>{state.repositoryCollections.map(collection=><option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label><Button className="repository-new-group" icon="new-folder" aria-expanded={createGroup} onClick={()=>setCreateGroup(current=>!current)} disabled={phase==='submitting'}>{createGroup?t('Use Existing Group','使用现有分组'):t('New Group','新建分组')}</Button>{createGroup&&<label className="form-field"><span>{t('New group name','新分组名称')}</span><input value={groupName} maxLength={80} onChange={event=>setGroupName(event.target.value)} data-autofocus="true"/></label>}</div>}
    </>}
  </Modal>;
}
