import { Button, Icon, Modal } from './ui';

import { uiText } from './text';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { AddRepositoriesResult, RepositoryCollection, RepositoryDiscoveryPreview } from '../src/protocol/types';
import { rpc, subscribe } from './rpc';
import { useTranslation } from './i18n';

import { useWorkbench } from './store';
import { selectionForClick } from './commitSelection';

type Phase='choose'|'scanning'|'results'|'submitting';
type AddMode='repository'|'group';

export function RepositoryDialog({onClose}:{onClose():void}){
  const state=useWorkbench(),t=useTranslation(),[phase,setPhase]=useState<Phase>('choose'),[root,setRoot]=useState(''),[preview,setPreview]=useState<RepositoryDiscoveryPreview>(),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[collectionId,setCollectionId]=useState(''),[createGroup,setCreateGroup]=useState(false),[groupName,setGroupName]=useState(''),[progress,setProgress]=useState({scanned:0,found:0}),[error,setError]=useState<string>(),scanId=useRef<string|undefined>(undefined),generation=useRef(0),anchor=useRef<string|undefined>(undefined);
  const [mode,setMode]=useState<AddMode>('repository'),[newName,setNewName]=useState(''),[creating,setCreating]=useState(false),[picking,setPicking]=useState(false),groupInput=useRef<HTMLInputElement>(null),destinationInput=useRef<HTMLInputElement>(null),busy=creating||phase==='submitting';
  useEffect(()=>{if(mode==='group')groupInput.current?.focus();},[mode]);
  useEffect(()=>{if(createGroup&&mode==='repository')destinationInput.current?.focus();},[createGroup,mode]);
  const nameProblem=(value:string)=>{const name=value.trim();return !name?t("repositoriesDialog.enterAGroupName"):name.length>80?t("repositoriesDialog.useNoMoreThan80Characters"):state.repositoryCollections.some(collection=>collection.name.localeCompare(name,undefined,{sensitivity:'accent'})===0)?t("repositoriesDialog.aGroupWithThisNameAlreadyExists"):undefined;};
  const newNameProblem=newName?nameProblem(newName):undefined;
  const destinationNameProblem=groupName?nameProblem(groupName):undefined;
  useEffect(()=>subscribe(event=>{if(event.type==='repositoryDiscoveryProgress'&&event.scanId===scanId.current)setProgress({scanned:event.scanned,found:event.found});}),[]);
  const available=preview?.candidates.filter(candidate=>!candidate.existing)??[],filtered=useMemo(()=>{const query=search.trim().toLocaleLowerCase();return preview?.candidates.filter(candidate=>!query||candidate.name.toLocaleLowerCase().includes(query)||candidate.path.toLocaleLowerCase().includes(query))??[];},[preview,search]),selectedSet=new Set(selected),allSelected=available.length>0&&available.every(candidate=>selectedSet.has(candidate.key));
  const stopScan=()=>{generation.current++;const id=scanId.current;scanId.current=undefined;if(id)void rpc('cancelRepositoryDiscovery',undefined,{scanId:id});};
  const close=()=>{stopScan();onClose();};
  const switchMode=(next:AddMode)=>{if(busy||next===mode)return;generation.current++;if(phase==='scanning'){stopScan();setPhase('choose');}setError(undefined);setMode(next);};
  const createCollection=async()=>{const problem=nameProblem(newName);if(problem){setError(problem);return;}if(busy)return;setError(undefined);setCreating(true);try{const collection=await rpc<RepositoryCollection>('createRepositoryCollection',undefined,{name:newName.trim()});await state.initialize();useWorkbench.setState({notice:t("repositoriesDialog.createdGroup", { name: (collection.name) })});close();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setCreating(false);}};
  const scan=async(path:string)=>{stopScan();const request=++generation.current,id=uiText("repositoriesDialog.scan", { value: (Date.now()), request: (request) });scanId.current=id;setRoot(path);setPreview(undefined);setSelected([]);setSearch('');setProgress({scanned:0,found:0});setError(undefined);setPhase('scanning');try{const result=await rpc<RepositoryDiscoveryPreview>('discoverRepositories',undefined,{scanId:id,path});if(request!==generation.current)return;if(result.cancelled){setPhase('choose');return;}setPreview(result);setSelected(result.candidates.filter(candidate=>!candidate.existing).map(candidate=>candidate.key));setPhase('results');}catch(reason){if(request!==generation.current)return;setError(reason instanceof Error?reason.message:String(reason));setPhase('choose');}};
  const choose=async()=>{if(picking)return;const request=++generation.current;setPicking(true);setError(undefined);try{const path=await rpc<string|undefined>('pickRepositoryDirectory');if(path&&request===generation.current)await scan(path);}catch(reason){if(request===generation.current)setError(reason instanceof Error?reason.message:String(reason));}finally{setPicking(false);}};
  const cancelScan=()=>{stopScan();setPhase('choose');setProgress({scanned:0,found:0});};
  const toggle=(key:string,event:{shiftKey:boolean;ctrlKey:boolean;metaKey:boolean})=>{const order=filtered.filter(candidate=>!candidate.existing).map(candidate=>candidate.key),next=selectionForClick(order,selected,anchor.current,key,{toggle:event.ctrlKey||event.metaKey,range:event.shiftKey});setSelected(next.selected);anchor.current=next.anchor;};
  const add=async()=>{if(!selected.length||busy)return;if(createGroup&&nameProblem(groupName)){setError(nameProblem(groupName));return;}setError(undefined);setPhase('submitting');try{const result=await rpc<AddRepositoriesResult>('addRepository',undefined,{scanId:scanId.current,keys:selected,...(!createGroup&&collectionId?{collectionId}:{}),...(createGroup?{newCollectionName:groupName.trim()}: {})});await state.initialize();useWorkbench.setState({notice:t("repositoriesDialog.addedRepositories", { added: (result.added), value: (result.collection ? t("repositoriesDialog.to", { name: (result.collection.name) }) : ''), value2: (result.existing ? t("repositoriesDialog.alreadyAdded", { existing: (result.existing) }) : ''), value3: (result.skipped ? t("repositoriesDialog.skipped", { skipped: (result.skipped) }) : '') }),selectedRepositoryKeys:[],repositorySelectionAnchor:undefined});scanId.current=undefined;onClose();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setPhase('results');}};
  const footer=phase==='choose'?null:phase==='scanning'?<Button onClick={cancelScan}>{t("repositoriesDialog.cancelScan")}</Button>:<><span className="repository-add-summary" aria-live="polite">{t("repositoriesDialog.selected", { count: (selected.length) })}</span><Button onClick={close} disabled={phase==='submitting'}>{t("common.cancel")}</Button><Button className="primary" onClick={()=>void add()} disabled={!selected.length||phase==='submitting'||createGroup&&!!nameProblem(groupName)}>{phase==='submitting'?t("repositoriesDialog.adding"):t("repositoriesDialog.addRepositories", { count: (selected.length) })}</Button></>;
  const groupFooter=<><Button onClick={close} disabled={busy}>{t("common.cancel")}</Button><Button type="submit" form="repository-create-group" className="primary" icon="new-folder" disabled={busy||!!nameProblem(newName)}>{creating?t("repositoriesDialog.creating"):t("repositoriesDialog.createGroup")}</Button></>;
  return <Modal title={t("repositoriesDialog.add")} className="repository-dialog" onClose={close} busy={busy} footer={mode==='group'?groupFooter:footer}>
    <div className="repository-add-tabs" role="tablist" aria-label={t("repositoriesDialog.addType")} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();switchMode(event.key==='Home'?'repository':event.key==='End'?'group':mode==='repository'?'group':'repository');}}}>
      <button type="button" id="add-repository-tab" role="tab" aria-selected={mode==='repository'} aria-controls="repository-add-panel" tabIndex={mode==='repository'?0:-1} className={mode==='repository'?'is-active':''} disabled={busy} onClick={()=>switchMode('repository')}><Icon name="repo"/>{t("repositoriesDialog.addRepository")}</button>
      <button type="button" id="add-group-tab" role="tab" aria-selected={mode==='group'} aria-controls="repository-add-panel" tabIndex={mode==='group'?0:-1} className={mode==='group'?'is-active':''} disabled={busy} onClick={()=>switchMode('group')}><Icon name="new-folder"/>{t("repositoriesDialog.addGroup")}</button>
    </div>
    {error&&<div className="banner error" role="alert"><span>{error}</span></div>}
    <div id="repository-add-panel" className="repository-add-panel" role="tabpanel" aria-labelledby={mode==='group'?'add-group-tab':'add-repository-tab'}>
    {mode==='group'?<form id="repository-create-group" className="repository-group-form" onSubmit={event=>{event.preventDefault();void createCollection();}}>
      <h3>{t("repositoriesDialog.createGroup")}</h3>
      <p className="repository-dialog-intro">{t("repositoriesDialog.createAGroupToOrganizeRepositoriesYouCanAdd")}</p>
      <label className="form-field"><span>{t("repositoriesDialog.groupName")}</span><input ref={groupInput} placeholder={t("repositoriesDialog.groupNameExample")} value={newName} maxLength={80} disabled={busy} aria-invalid={!!newNameProblem||!!error} aria-describedby={newNameProblem?'repository-group-error':undefined} onChange={event=>{setNewName(event.target.value);setError(undefined);}}/></label>
      {newNameProblem&&<div id="repository-group-error" className="repository-name-error" role="alert">{newNameProblem}</div>}
    </form>:<>
    {phase==='choose'&&<div className="repository-folder-empty"><Icon name="folder-opened"/><strong>{root?t("repositoriesDialog.chooseAnotherFolderOrScanThisFolderAgain"):t("repositoriesDialog.chooseRepositoryFolder")}</strong>{root&&<code>{root}</code>}<p className="repository-dialog-intro">{t("repositoriesDialog.folderChoiceHint")}</p><p className="repository-dialog-intro">{t("repositoriesDialog.scanConfirmationHint")}</p><Button className="primary" icon="folder-opened" data-autofocus="true" disabled={picking} onClick={()=>void choose()}>{t("repositoriesDialog.chooseFolder")}</Button></div>}
    {phase==='scanning'&&<div className="repository-scanning" aria-live="polite"><Icon name="loading" className="feedback-spinner"/><div><strong>{t("repositoriesDialog.scanningForGitRepositories")}</strong><code>{root}</code><span>{t("repositoriesDialog.scannedFoldersFoundRepositories", { scanned: (progress.scanned), found: (progress.found) })}</span></div></div>}
    {(phase==='results'||phase==='submitting')&&preview&&<>
      <div className="repository-scan-header"><div><span>{t("repositoriesDialog.scanFolder")}</span><code title={root}>{root}</code></div><Button className="icon-only" icon="folder-opened" title={t("repositoriesDialog.chooseAnotherFolder")} aria-label={t("repositoriesDialog.chooseAnotherFolder")} disabled={phase==='submitting'||picking} onClick={()=>void choose()}/></div>
      <div className="repository-result-summary"><strong>{t("repositoriesDialog.foundRepositories", { count: (preview.candidates.length) })}</strong><span>{t("repositoriesDialog.availableAlreadyAdded", { count: (available.length), count2: (preview.candidates.length-available.length) })}</span></div>
      {preview.candidates.length?<><div className="repository-result-tools"><label><Icon name="search"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={t("repositoriesDialog.filterRepositories")} aria-label={t("repositoriesDialog.filterRepositories")}/></label><label className="form-checkbox"><input type="checkbox" checked={allSelected} onChange={event=>setSelected(event.target.checked?available.map(candidate=>candidate.key):[])}/>{t("repositoriesDialog.selectAllAvailable")}</label></div>
      <div className="repository-candidate-list" role="listbox" aria-multiselectable="true" aria-label={t("repositoriesDialog.discoveredRepositories")}>{filtered.length?filtered.map(candidate=><label key={candidate.key} className={`repository-candidate ${candidate.existing?'existing':''}`} role="option" aria-selected={!candidate.existing&&selectedSet.has(candidate.key)}><input type="checkbox" disabled={candidate.existing||phase==='submitting'} checked={!candidate.existing&&selectedSet.has(candidate.key)} readOnly onClick={event=>{event.preventDefault();toggle(candidate.key,event);}}/><span><strong>{candidate.name}</strong><code title={candidate.path}>{candidate.path}</code></span>{candidate.existing&&<small>{t("repositoriesDialog.alreadyAddedVariant2")}</small>}</label>):<div className="repository-filter-empty">{t("repositoriesDialog.noRepositoriesMatchThisFilter")}</div>}</div></>:<div className="repository-result-empty"><Icon name="search-stop"/><strong>{t("repositoriesDialog.noGitRepositoriesFound")}</strong><span>{t("repositoriesDialog.chooseADifferentFolderAndTryAgain")}</span></div>}
      {!!preview.issues.length&&<details className="repository-scan-issues"><summary>{t("repositoriesDialog.foldersOrRepositoriesWereSkipped", { count: (preview.issues.length) })}</summary>{preview.issues.map(issue=><div key={`${issue.path}:${issue.message}`}><code>{issue.path}</code><span>{issue.message}</span></div>)}</details>}
      {!!available.length&&<div className="repository-destination">
        <label className="form-field"><span>{t("repositoriesDialog.addTo")}</span>{createGroup?<input ref={destinationInput} value={groupName} maxLength={80} placeholder={t("repositoriesDialog.groupNameExample")} aria-label={t("repositoriesDialog.newGroupName")} aria-invalid={!!destinationNameProblem} aria-describedby={destinationNameProblem?'repository-destination-error':'repository-destination-hint'} disabled={phase==='submitting'} onChange={event=>{setGroupName(event.target.value);setError(undefined);}}/>:<select value={collectionId} onChange={event=>setCollectionId(event.target.value)} disabled={phase==='submitting'}><option value="">{t("repositoriesDialog.repositoryRoot")}</option>{state.repositoryCollections.map(collection=><option key={collection.id} value={collection.id}>{collection.name}</option>)}</select>}</label>
        <Button className="repository-new-group icon-only" icon={createGroup?'close':'add'} title={createGroup?t("repositoriesDialog.useExistingGroup"):t("repositoriesDialog.newGroup")} aria-label={createGroup?t("repositoriesDialog.useExistingGroup"):t("repositoriesDialog.newGroup")} aria-expanded={createGroup} onClick={()=>{setCreateGroup(current=>!current);setError(undefined);}} disabled={phase==='submitting'}/>
        {createGroup&&(destinationNameProblem?<div id="repository-destination-error" className="repository-name-error" role="alert">{destinationNameProblem}</div>:<p id="repository-destination-hint" className="repository-dialog-intro">{t("repositoriesDialog.createGroupAndAddHint")}</p>)}
      </div>}
    </>}
    </>}
    </div>
  </Modal>;
}
